CREATE TABLE IF NOT EXISTS teste (
    id SERIAL PRIMARY KEY,
    nome VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP
);

DROP TABLE IF EXISTS teste;

CREATE TABLE IF NOT EXISTS teste (
    cpf VARCHAR(11) NOT NULL,
    nome VARCHAR(50) NOT NULL,
    created_at TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
	PRIMARY KEY (cpf)
);

INSERT INTO teste (cpf, nome, created_at)
VALUES ('31721103941','Mylena Tartarya', '2020-12-03 12:47:00');

INSERT INTO teste (cpf, nome, created_at)
VALUES ('31721103941','Mylena Tartarya', '2020-12-03 12:47:00') ON CONFLICT (cpf) DO NOTHING;

UPDATE teste SET nome = 'Kitana Kham' WHERE cpf = '31721103941';

SELECT * FROM teste;